### ISSUE TITLE
Add GUI Features to superforth

### ISSUE THREAD

**Issue by Xanderplayz16** [TheRealMichaelWang/cish#29]

**Comment by TheRealMichaelWang** [comment]
A GUI is something that will eventually be implement in the future, however at the current moment there are a few more pressing priorities that will be implemented first.
- The most immediate priority is to finish the dynamic casting and run time type information upgrades to SuperForth, which can be found in the upcast branch.
- Integration with C#. Please check out the SuperForthCSharp project which already works with a slightly earlier version of SuperForth. This is probably the second most immediate priority.
- An IDE, or at least a language server

The reason why a GUI isn't a pressing concern at the moment is because it can already be done, using the existing tools at hand. Use the FFI to interop with any C GUI library of your choice(must be a dynamically linked library), or use SuperForthCSharp to interop with winforms or wpf.

Any help is welcome. I'd be glad if you're up to implementing a gui library for SuperForth. These are simply the priorities given the limited resources and time I have.

**Comment by Xanderplayz16** [comment]
Ok.

**Comment by TheRealMichaelWang** [comment]
This issue is a work in progress, and will not be closed until the feature is added.

**Comment by xandaaah** [comment]
Closing because this project is dead.
